### ISSUE TITLE
BlazorHybrid WebView does not render

### ISSUE THREAD

**Issue by markzielinski** [dotnet/MobileBlazorBindings#223]
I'm having an issue where the WebView is not rendering correctly when using the default BlazorHybrid application.

The error message is:
It looks like the webpage at http://0.0.0.0/ might be having issues, or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

I'm using the latest Windows 10 insider preview build (20251.1) with the latest Mobile Blazor Bindings template (0.5.50-preview) and I also have the latest Edge Canary installed (88.0.696.0 canary 64-bit)

![Issue](https://user-images.githubusercontent.com/1417339/98733286-ebd1db00-2365-11eb-958e-618c36f0029b.png)

**Comment by Eilon** [comment]
Well that's not good!

Can you try running the app in the debugger with _ALL_ CLR exceptions caught?

![image](https://user-images.githubusercontent.com/202643/98734133-63980980-2356-11eb-906c-1113f96d1d4b.png)

**Comment by markzielinski** [comment]
I made that change and I don't see any differences.   If I click on the increment button it does show an Unhandled exception with "One or more errors occurred. (Render was called before InitAsync)".

There are some compile warnings for:
Xamarin.Forms recommends TargetPlatformMinVersion >= 10.0.14393.0 (current project is -1)
Xamarin.Forms recommends TargetPlatformVersion >= 10.0.17763.0 (current project is -1)

![1](https://user-images.githubusercontent.com/1417339/98739863-bc27d080-236f-11eb-80c5-51da92673028.PNG)

**Comment by Eilon** [comment]
Yeah once Blazor fails to load you'll get an exception on almost anything you click, so that failure is expected.

We'll have to take a look at this because usually there would be some exception somewhere.

This is just the 100% default template, or were any changes at all made?

**Comment by markzielinski** [comment]
Yes exactly, I didn't make any changes and this is the default template for blazorhybrid.

**Comment by Eilon** [comment]
Well that's definitely weird so we'll take a look at this. By all accounts your setup should be fine but clearly there's something missing here.

**Comment by markzielinski** [comment]
OK, I have this working without any issues now.  I had all of the Edge insider previews installed and once I removed the beta preview it immediately worked.   Once I reinstalled the beta preview I had the same problem again.  It seems like somehow the beta preview is taking precedence over the canary preview.

**Comment by bddckr** [comment]
I had the same issue just now, also with just the `blazorhybrid` template used with no modifications.

I'm on Windows 10 and had the WebView2 runtime installed (version 86.0.622.63 it said in Control Panel). I had no Edge Beta, Dev or Canary installed.

To workaround the issue I've installed Edge Dev and it's working fine now.

**Comment by rChavz** [comment]
if we comment the next lines in file Main.razor the button works fine

```
        @*<BlazorWebView VerticalOptions="LayoutOptions.FillAndExpand">
            <Vndi24Mobil.WebUI.App />
        </BlazorWebView>*@
```

**Comment by Elfahor** [comment]
Same issue, I have no Edge Beta nor Dev, only the default and Canary.

**Comment by kngsly** [comment]
Having same issue, it only seems to be happening when I press F5 inside of the Windows App or mess up some Navigation Manager routing.

I'll post if I find a solution that doesn't involve a Edge Beta/Dev workaround.

**Comment by jburman** [comment]
I started getting the http://0.0.0.0/ ERR_ADDRESS_INVALID across multiple client machines after recent Edge auto updates. Installing the WebView2 runtime was the only way that I found to resolve it.

**Comment by rajeshsws** [comment]
I am also getting same error http://0.0.0.0/ ERR_ADDRESS_INVALID across multiple client machines after recent Edge auto updates. Installing the WebView2 runtime was the only way that I found to resolve it.

**Comment by ColonelDuddits** [comment]
I also had this issue. Manually adding the Microsoft.Web.WebView2 nuget package to the project fixed it for me.

**Comment by 0x78f1935** [comment]
> I also had this issue. Manually adding the Microsoft.Web.WebView2 nuget package to the project fixed it for me. I also have Canary installed.

This also worked for me! Thank you!

**Comment by benny856694** [comment]
> I also had this issue. Manually adding the Microsoft.Web.WebView2 nuget package to the project fixed it for me. I also have Canary installed.

this saved my day, really helpful
