### ISSUE TITLE
ShellNavigationManager throws error if it find url "/"

### ISSUE THREAD

**Issue by lachlanwgordon** [dotnet/MobileBlazorBindings#293]
Shell Navigation manager throws error `System.ArgumentNullException: 'Route cannot be an empty string
Parameter name: route'` if it finds the route "/". I found this when I tried to have a BlazorWebView and a Shell in the same project.

The easy fix is to have ShellNavigationManager ignore "/", but longer term we may want a way to distinguish between XF Razor Components and Web Razor Components within the same project. I'll make a note of this in the known problems issue.

**Comment by Eilon** [comment]
> longer term we may want a way to distinguish between XF Razor Components and Web Razor Components within the same project

Definitely this! But for now I agree we should just ignore pages with such routes when we talk to Xamarin.Forms' Shell routing system.

**Comment by Eilon** [comment]
Fixed by #294
