### ISSUE TITLE
Shell navigation does not happen until OnInitialyzedAsync fully executed

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/MobileBlazorBindings#300]
STR:
1. Create Page component with @page directive.
2. Override OnInitializedAsync, put `await Task.Delay(10000);` there.
3. Use ShellNavigationManager to navigate to this page component.

ER: 
Navigation happens immediately. Page is re-rendered after 10s, when OnInitializedAsync is executed.

AR:
Navigation only happens after 10 seconds.

**Comment by Dreamescaper** [comment]
Problem is that RenderRootComponentAsync method performs full initial rendering, including execution of asynchronous methods and performing re-rendering.

That didn't happen before #298 , as rendering was performed in fire-and-forget way.

**Comment by Dreamescaper** [comment]
I have an idea how to fix that, not sure how great it is though.
Currently we await rendering to RootContainerHandler, than retrieve XF.Page from there and use it for navigation.

We can probably wait for the first element added to RootContainerHandler instead, and use it for navigation straight away, without awaiting for rendering completed.

**Comment by Eilon** [comment]
> We can probably wait for the first element added to RootContainerHandler instead, and use it for navigation straight away, without awaiting for rendering completed.

I think that's definitely worth a shot, assuming the UI thread is even available to do the work (otherwise it'll just wait anyway until it's available).

**Comment by Dreamescaper** [comment]
I think it should be available, considering that it worked previously, when rendering was executed in fire-and-forget manner.
