### ISSUE TITLE
Shell navigation crashes if another navigation is in progress

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/MobileBlazorBindings#302]
In #291 ShellNavigationManager was updated to use the same singleton renderer instead of creating a new one on each navigation. That change leads to issue - if I invoke multiple navigations in short period of time, or if I put navigation to component's OnInitialyzedAsync method, navigation will crash due to rendering exception:
```
InvalidOperationException: There is an ongoing rendering in progress.
```

So apparently that singleton change should be reverted.

**Comment by Dreamescaper** [comment]
I'm still curious though, where we should dispose created renderers. 
I think it would make sense to do that when Page is removed from NavigationStack (as disposing the renderer seems to Dispose all rendered components as well).
Would it make place to handle that in ShellNavigationManager? Or some other place?

**Comment by Eilon** [comment]
Hmm... maybe it's OK to have a singleton renderer but we just need to protect access to it?

If we do need to create multiple renderers then I guess wherever we create them we need to ensure they are disposed. If creating them is done as part of ShellNavigationManager, then that component needs to dispose them as well (or make sure that disposal is hooked up).

**Comment by Dreamescaper** [comment]
> Hmm... maybe it's OK to have a singleton renderer but we just need to protect access to it?

Not sure if we can do that properly, considering that rendering process includes component's async methods. So if even if we serialize access somehow, that could cause that some hanged request in OnInitialyzedAsync will block app navigation, which doesn't sound great.
