### ISSUE TITLE
z-index support

### ISSUE THREAD

**Issue by Kylar182** [dotnet/MobileBlazorBindings#326]
Will z-index from CSS ever be supported?

**Comment by Dreamescaper** [comment]
Web elements inside of WebView for hybrid apps should support z-index (as any other web content).

Native apps probably won't support z-index, as it is not supported by underlying Xamarin.Forms framework.

**Comment by Eilon** [comment]
Pretty much what @Dreamescaper said.

@Kylar182 - can you share more info about what exactly isn't working or what you'd like to see?

**Comment by Kylar182** [comment]
Well, the I've built 1 prod Xamarin App from ground up, a few Blazor apps and 1 WPF app. The main issue with XAML is how much layering of layouts it takes and how verbose it becomes to do simple things like z-index. What I'm hoping to accomplish is to be able to use Bootstrap's Flex Grid with z-index to build layouts like I do in Blazor.

**Comment by Eilon** [comment]
So you want to use CSS z-index for _native_ controls, such as StackLayout, Button, Entry, or for HTML controls, such as `<input type="..." />`, `<div ... />`, etc.?
