### ISSUE TITLE
.Net 5 support

### ISSUE THREAD

**Issue by zachneu** [dotnet/MobileBlazorBindings#341]
When will this support existing .net 5 nuget packages (for blazor components)?
Today we are develivering a blazor web application (both wasm and server rendered) and would like to use existing code to translate it into a mobile app. 

Because of the policies of google play and app store, the app we want to deliver might not be approved and we dont want to spend too much on developing the app - but with the posibilities to reuse existing blazor components we can build the app quit fast and check if its something to continue with or not.

**Comment by Eilon** [comment]
Hi @zachneu this project currently uses .NET Core 3.1 and we will soon migrate it to .NET 6. We can't support .NET5 because there is no support for Xamarin.Forms on .NET 5, and that is required for hosting these components.

**Comment by SamazoOo** [comment]
HI @Eilon , is it .NET MAUI? is Mobile blazor bindings release with .NET 6 ? awesome project!

**Comment by Eilon** [comment]
Hi @SamazoOo parts of Mobile Blazor Bindings will be built-in the .NET 6 based on .NET MAUI. In particular, there will be a BlazorWebView control for hosting Blazor web content in native desktop apps. The parts of Mobile Blazor Bindings for building native UI will remain experimental for the time being.

**Comment by Eilon** [comment]
Closing this because we don't plan to support .NET 5, but we will instead move to .NET 6, per this issue: https://github.com/dotnet/MobileBlazorBindings/issues/352
