### ISSUE TITLE
iOS samples does not work on Local Device

### ISSUE THREAD

**Issue by Ogglas** [dotnet/MobileBlazorBindings#351]
Tested `MobileBlazorBindingsHelloWorld.iOS` and `MobileBlazorBindingsTodo.iOS`. Used original code, only change is `iOS Bundle Signing` set to `Automatic Provisioning` with my developer certificate and marked projects as "Deploy" in Configuration Manager.

Tried to start with Debug and simply Deploy the release version but none of them work. 

I can see the app but if I click on it the app will crash instantly.

Tested on iPhone 12 Pro Max with iOS 14.4.1.

**Comment by Eilon** [comment]
Hi @Ogglas can you share any more info on the crash? Does the app run on the iOS Simulator?

**Comment by Ogglas** [comment]
@Eilon Got it working by specifying `Supported Architectures: ARMv7 + ARMv7s + ARMv64` under iOS Build and cleaned the solution. Closing this issue.

**Comment by Eilon** [comment]
I'm glad you got it working! I had previously run into a somewhat similar issue with Android: https://github.com/xamarin/xamarin-android/issues/5388

If you think this is a bug with deploying to iOS, please file a bug on https://github.com/xamarin/xamarin-macios
