### ISSUE TITLE
Blazor in vanilla WPF ? 

### ISSUE THREAD

**Issue by deanchalk** [dotnet/MobileBlazorBindings#354]
It seems that if you want to host Blazor in a WPF app that runs natively you need these mobile bindings., which in turn only allow you to do this via Xamarin Forms.
Is there any possibility of doing this in a non-Xamarin app - i.e. straight WPF
I'm trying to migrate a legacy WPF app over to Blazor bit by bit, without having to host the blazor on a remote server.

Any plans on supporting standard WPF - I think this would be a lot more useful to the client dev community if it did

Many thanks

**Comment by Eilon** [comment]
Yes, this is already in .NET 6! https://github.com/dotnet/aspnetcore/issues/30511

Note that it's in a very early stage, but it will be available in the next preview, which will be .NET 6 Preview 3. This is a very simple sample app: https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebView/Samples/BlazorWpfApp
