### ISSUE TITLE
Radzen Blazor not working

### ISSUE THREAD

**Issue by mg1357** [dotnet/MobileBlazorBindings#364]
I installed Radzen Blazor package in the main project and then write @using Radzen.Blazor and @using Radzen in both _imports
Then Referenced its script and css in all projects (in their index.html), Now when I open a tag in the MainLayout.razor file there is no Radzen tags recognized by Intellisense, How to do this?

**Comment by Akdimi** [comment]
Mayby because it is only conpatible with .net5. I had the same with Blazorise nuget package. Couldnt use the last version in Blazor hybrid. And older versions didnt work well either

**Comment by mg1357** [comment]
Yes I tried an older version and it is working now.

**Comment by Eilon** [comment]
Mobile Blazor Bindings currently works with only .NET Core 3.x. We intend to update it to .NET 6 in the future. (We can't support .NET 5 because Xamarin.Forms isn't compatible with .NET 5.)
