### ISSUE TITLE
Reusable blazor components

### ISSUE THREAD

**Issue by angelru** [dotnet/MobileBlazorBindings#376]
I have a web application in blazor wasm, I would like to reuse blazor wasm login and registration in my xamarin application, is there a way to use my 2 blazor components in xamarin?

my xamarin app is not blazor bindings.

**Comment by Eilon** [comment]
@angelru yes, in general you should be able to add a BlazorWebView control from Mobile Blazor Bindings to your Xamarin.Forms app, and you can then host your Blazor web components in that BlazorWebView.

**Comment by angelru** [comment]
@Eilon I have several doubts, my xamarin forms project is not from Mobile Blazor Bindings, I would have to install the nuget package and then the configurations no? then what I do not see clear is to put only my 2 components that I want to reuse, since I do not want the complete application.

**Comment by angelru** [comment]
@Eilon Thank you very much, I'll see what I can do ...

**Comment by Xyncgas** [comment]
so it's basically adding a browser in your xamarin app? My blazor component can't communicate with the others c# codes in my xamarin because they are running in a sandox inside a browser?

**Comment by Eilon** [comment]
@Xyncgas that isn't the case. _All_ the C# code in a Mobile Blazor Bindings app runs in the same process and can all "talk" to each other. There's no browser sandbox for the C# code, and there's no Web Assembly. The browser is _only_ used to render the HTML, and optionally run any custom JS that you might have (e.g. 3rd party component such a Bootstrap, or your own custom JS code).

**Comment by Xyncgas** [comment]
> @Xyncgas that isn't the case. _All_ the C# code in a Mobile Blazor Bindings app runs in the same process and can all "talk" to each other. There's no browser sandbox for the C# code, and there's no Web Assembly. The browser is _only_ used to render the HTML, and optionally run any custom JS that you might have (e.g. 3rd party component such a Bootstrap, or your own custom JS code).

Ohh, so people found a way to let the MBB App talk to the browser and tell it what to render, while MBBA itself not running in the browser? that's so cool !!! what kind of magic is this

**Comment by Eilon** [comment]
@Xyncgas both Mobile Blazor Bindings (experimental) and Blazor Desktop (supported) use the same technique to run the app. All the .NET code runs in the same process, it's just that the Blazor code _renders_ the HTML into a WebView control for the UI to show up. No C#/.NET code runs "in" the WebView control (so there's no Web Assembly here, and also no SignalR). I talk about this a bit on this video I recently made: https://www.youtube.com/watch?v=oNxUfPoAXac

**Comment by angelru** [comment]
Is there a new way or is what you told me in this thread the correct way? or do we have to wait for MAUI?

**Comment by Eilon** [comment]
@angelru the way this works is the same between Mobile Blazor Bindings and .NET MAUI w/ BlazorWebView. You can place your various Blazor components in a Razor Class Library (RCL) and then reference them from Blazor WebAssembly, Blazor Server, or Blazor Desktop (in .NET MAUI, WinForms, or WPF).
