### ISSUE TITLE
Path not supported - Build failure IOS - reminder

### ISSUE THREAD

**Issue by whann0205** [dotnet/MobileBlazorBindings#377]
Hello Eilon,
Got Stuck with that problem (see details on the original issue).
Have supplied you with the .csproj in the original issue.
Even tried to adapt your rezipe app to see where the problem comes from.
To say it short with that app including mudblazor produces no failure on the iphone.
It stops from developing my solution, since i have to know if that kind of thing is possible with
iphone.

Sorry that i opened a new issue but i do not know how to contact you or your team.
I am a Microsoft Partner but the only thing the partner portal offers is a web contact form.
And that github channel does not seem to have a discussion area.

Can you PLEASE help me to get my app running ?
Again under Android all if working perfectly!

**Comment by Eilon** [comment]
Hi @whann0205 this project is currently an "experimental" project and not officially supported, so we have limited resources to offer. I will try to take a look at your issue today.
