### ISSUE TITLE
Why MobileBlazorBindings

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/MobileBlazorBindings#379]
1. I thought blazor was for the web
2. we already have xamarin right
3. xamarin is planning to support windows too

**Comment by Eilon** [comment]
Hi @Xyncgas , Mobile Blazor Bindings is an experimental project where we're trying new ideas before deciding whether they should become part of .NET. The BlazorWebView component that started in Mobile Blazor Bindings is now part of .NET 6 and enables several new scenarios:

1. Building new web-based UI that can run locally on Windows, macOS, iOS, and Android, and also in a web browser
2. Modernizing parts of existing WPF and WinForms apps by adding web-based UI to them, enabling it to be shared in other platforms
3. Enabling developers who have web skills to use their knowledge to quickly build native desktop and mobile apps without learning a new UI platform

And certainly there are other scenarios. But these are some of the biggest ones that we think create a lot of value in the .NET platform.

**Comment by Xyncgas** [comment]
1. I admit it's tempting plus it's beautiful to have an app that can run both the native and on the web.
2. I think companies cares more about 'can I' than 'you can', people are saying xamarin has been there for a long time and they are more comfortable with it and the way I am seeing they don't want to move to a new technology because they sure can write code the way they are now while being comfortable that they are going to be sure they can do what they want to do (I am sorry this sentence is so long and it doesn't seem like ending) but instead there isn't a strong guarantee that the new technology is going to let people do what they want to do now and in the future because sometimes they can be what's stopping you and it's true for example for people who are learning a new language and they often feel like can't do anything and later when they are more familiar with it they get the feelings like they can only do what the language let them to do which even c++ has this problem and it was supposed to be easy it was supposed to let people get what they want to do done easily given that it's an existing pattern and practice and demand unless you are making something new then you are more than welcome and won't be to difficult to do it too, I am just letting you know.
3. I like the future where companies starting to hire web people over to do native apps, more job opportunity, it's just that some people are gonna look at them and say "damn the September it's never gonna end" lol

**Comment by Xyncgas** [comment]
Hey Eilon, I just want to say, I just learned how to spell your name and I like what you are doing and looking forward to use this amazing technology one day
