### ISSUE TITLE
Render direction should be reversed

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/MobileBlazorBindings#381]
Currently the rendering sequence looks similar to that:
Create element -> Add element -> set element properties -> create child elements -> add child elements to parent -> set child element properties -> ...

This behavior causes unnecessary renders, and therefore visual glitches and worse performance, and is discouraged by XF documentation. 
Besides, sometimes it causes errors, when element is not yet initialized properly (which are workarounded using some stub elements).

Probably we should investigate whether we can reverse this order, so that element is only added to the visual tree when all required properties are already set (and corresponding child elements are already added).

**Comment by Eilon** [comment]
Argh yes this would be great! This has long been an annoyance to me!

**Comment by Dreamescaper** [comment]
Another issue caused by this - not all events are invoked.
If I add OnAppearing event handler to ContentPage, and this page is my starting page - event handler is not invoked, since event is triggered right after element is added as a child element, which happens before event handler is set.
