### ISSUE TITLE
Splash Screen per platform?

### ISSUE THREAD

**Issue by johnmangam** [dotnet/MobileBlazorBindings#383]
Do we still create the splash screens per platform like https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen?

**Comment by Eilon** [comment]
@johnmangam for splash screens you would do the same thing as you would in any other Xamarin.Forms app, for which the overview is on https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/splashscreen. So, yes, for Android, the doc you mention would be the way to go.
