### ISSUE TITLE
Blazor Hybrid App (Windows) throws an exception when using JsInterop "too early"

### ISSUE THREAD

**Issue by Kukks** [dotnet/MobileBlazorBindings#386]
When using MBB with Windows with a fully Blazor Web UI, and the first page renders, and calls `OnAfterRenderAsync`, I get an exception stating that "AttachToIpcChannel must be called before using IJSRuntime". 

![image](https://user-images.githubusercontent.com/1818366/125091458-b5a15280-e0d0-11eb-843e-9295e2989bff.png)

Is there something I can check or await?

**Comment by Eilon** [comment]
Hi @Kukks does this look the same or similar to these previous issues?

* (you opened this one 😄) Hybrid Windows crash when using IJSRuntime early on page load - https://github.com/dotnet/MobileBlazorBindings/issues/259
* AttachToIpcChannel must be called before using IJSRuntime - https://github.com/dotnet/MobileBlazorBindings/issues/218

**Comment by Kukks** [comment]
> Hi @Kukks does this look the same or similar to these previous issues?
> 
> * (you opened this one 😄) Hybrid Windows crash when using IJSRuntime early on page load - [Hybrid Windows crash when using IJSRuntime early on page load #259](https://github.com/dotnet/MobileBlazorBindings/issues/259)
> * AttachToIpcChannel must be called before using IJSRuntime - [AttachToIpcChannel must be called  before using IJSRuntime #218](https://github.com/dotnet/MobileBlazorBindings/issues/218)

Hah, seems like I'm falling down the same pitfalls as I start gearing up again to using MBB :)

It was indeed solved by ensuring all services that use IJsRuntime are configured as Transient or Scoped!
