### ISSUE TITLE
Disable CORS for Android app

### ISSUE THREAD

**Issue by tabachuk** [dotnet/MobileBlazorBindings#398]
I get this error when I try to access an image through JS code. How can I resolve this problem? Is it possible to disable CORS in MBB somehow?
![image](https://user-images.githubusercontent.com/25420400/127867387-516fd285-1c6c-406c-99d0-f9f28159323a.png)

**Comment by Eilon** [comment]
Hmm interesting. In general, I don't think CORS shouldn't play any significant role in BlazorWebView scenarios. What is the request that's trying to access that URL?

**Comment by tabachuk** [comment]
Oh, sorry. The problem was in my JavaScript code, I'm not very good in JS yet. Thanks, @Eilon!
