### ISSUE TITLE
Open-Iconic doesn't work

### ISSUE THREAD

**Issue by Sl4vP0weR** [dotnet/MobileBlazorBindings#400]
![image](https://user-images.githubusercontent.com/42337892/129564781-16123fba-02a6-4a3a-9519-5696d6cf914a.png)
![image](https://user-images.githubusercontent.com/42337892/129564724-e23458c7-9809-439f-bd75-e56d472df78d.png)

**Comment by Eilon** [comment]
Hmm interesting. Is this from the default project template, or is this with some other version of the fonts?

**Comment by Sl4vP0weR** [comment]
@Eilon, Yes, this is default project template. I think that problem in the WebView

**Comment by Sl4vP0weR** [comment]
Unrelevant
