### ISSUE TITLE
Icon path is not working in AppShell.razor

### ISSUE THREAD

**Issue by johnmangam** [dotnet/MobileBlazorBindings#407]
I'm using 0.6.69-preview of MBB

In the **AppShell.razor the icon path is not recognized**, I tried placing the png in wwwroot and also the project root folder as a content (build type).

`<Shell BackgroundColor="XF.Color.Black">
    <TabBar Title="Something">
        <Tab Title="Articles" Icon="something.png">
            <ShellContent>
           ...
            </ShellContent>
        </Tab>`

**Comment by johnmangam** [comment]
Sorry, I just referred the MMB Xaminals example and found that I need to use:
`Icon="@(new FileImageSource { File="paw.png" })`

Thank you so much for those thoughtful samples.

**Comment by Dreamescaper** [comment]
Just an additional suggestion.
Put that FileImageSource to the field instead of creating it razor directly - it will help to avoid visual glitches (we need to update that sample).

**Comment by johnmangam** [comment]
Thank you so much for the suggestion, @Dreamescaper
