### ISSUE TITLE
Unable to customize TitleView of NavBar (add few elements) in Razor component - Shell / ContentPage

### ISSUE THREAD

**Issue by johnmangam** [dotnet/MobileBlazorBindings#410]
I would like to add a few more elements to the TitleView of NavBar.

I'm able to see this NavigationPage.TitleView in XAML https://github.com/xamarin/xamarin-forms-samples/blob/main/Navigation/TitleView/NavigationPageTitleView/NavigationPageTitleView/Views/AndroidExtendedTitleViewPage.xaml

I am not able to do the same in **razor of Shell or a ContentPage**. Please help, thank you.

**Comment by Dreamescaper** [comment]
Unfortunately, this property is not yet mapped in MBB.

**Comment by johnmangam** [comment]
Thank you @Dreamescaper I see that there is  Shell.TitleView. Could we use it in a Razor component?

**Comment by Dreamescaper** [comment]
That one is not mapped either.
If you really need to, you can access native Xamarin.Forms elements, and assign that property directly, but you'll need to build that TitleView using native XF elements, you won't be able to use razor there.

You can read about that here:
https://docs.microsoft.com/en-us/mobile-blazor-bindings/advanced/access-native-controls#accessing-native-xamarinforms-controls-from-blazor-components

**Comment by johnmangam** [comment]
Thank you for the information, @Dreamescaper

**Comment by Dreamescaper** [comment]
I think you can leave it open - as a request to map those properties in MBB.
