### ISSUE TITLE
Bootstrap CSS without at-rules for MBB

### ISSUE THREAD

**Issue by johnmangam** [dotnet/MobileBlazorBindings#411]
Hi,

I see that **At-rules are not supported for MBB yet**. Could anyone tell me where I could find a **bootstrap css or other css templates** without at-rules for mobile app?

When I use a **Page**, using bootstrap is easy because I use HTML. The moment I start using a **Shell**, I am mandated to use a **ContentPage** and in **ContentPage HTML is not allowed** unlike in a Page. This forces me to use controls and style css without at-rules. Is this is the expected behavior, please?

**Comment by BenMakesGames** [comment]
I've been using `@media` rules successfully, including `@media print`... but that's the _only_ "at rule" I've tried so far.

**Comment by johnmangam** [comment]
@BenMakesGames O, great! Is it in a Shell's ContentPage?

**Comment by Eilon** [comment]
There are two places to use CSS in Mobile Blazor Bindings:

1. For native UI elements there is some limited CSS usage, which you can read about here: https://docs.microsoft.com/en-us/mobile-blazor-bindings/ui/css-styles
2. For hybrid apps the HTML UI in a BlazorWebView has full CSS support (well, I'm sure there's _some_ limitation, but not much)

**Comment by johnmangam** [comment]
Thank you so much for the information, @Eilon
