### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by nextfool** [dotnet/MobileBlazorBindings#414]
Hello,
I came across this project recently, and found it's the ultimate answer to traditional asp.net (core) web developers like me to enter the mobile app development realm.  The only problem is seems there are not many activities in this repo, the last version is release d in last October,  which is almost a year ago. I just want to ask the folks here, is this project still alive? when will be the first production ready release? Thank you very much.

**Comment by Eilon** [comment]
Hi @nextfool , you can read more about the project status on these issues:

* https://github.com/dotnet/MobileBlazorBindings/issues/338
* https://github.com/dotnet/MobileBlazorBindings/issues/405
