### ISSUE TITLE
Running a project for Mobile Blazor Bindings failed for Windows app

### ISSUE THREAD

**Issue by Bronzato1** [dotnet/MobileBlazorBindings#427]
I tried to follow the 'Get Started' for Creating an app with Experimental Mobile Blazor Bindings

https://docs.microsoft.com/fr-fr/mobile-blazor-bindings/walkthroughs/build-first-hybrid-app

So I create my project by running this command:

dotnet new blazorhybrid -o FirstBlazorHybridApp

I can open the solution in Visual Studio 2019 and compile without problems.

I can even run the project inside the Android simulator. In Solution Explorer, right-click on the Android project and select Set as StartUp Project.

![a](https://user-images.githubusercontent.com/13705487/140288815-a5a2a82c-cc87-44f3-a4a3-e85cd7a9ac28.png)

Unfortunately running the project for a Windows app failed.

![b](https://user-images.githubusercontent.com/13705487/140288853-d828b304-cd24-4982-aaec-75a5e81546e0.png)

I have no idea what may be the problem.

**Comment by Eilon** [comment]
Hi @Bronzato1 , add this package reference to the MyProjectName.Windows.csproj project:

```xml
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.961.33" />
```

And the problem should go away. This will be fixed in the next update!

**Comment by Bronzato1** [comment]
It works. Thanks!
