### ISSUE TITLE
[question] how is blazor hybrid running(if) javascript & css without a browser / browser sandbox

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/MobileBlazorBindings#429]

**Comment by Eilon** [comment]
Hi @Xyncgas , all the app code in Blazor Hybrid apps runs as native code on the device (including both in Mobile Blazor Bindings, and in BlazorWebView for .NET MAUI, WPF, and WinForms). This is unlike Blazor WebAssembly where the app code runs _in the browser_, where there is a sandbox.

The code in Blazor Hybrid apps (both "regular" code, and "Blazor" code in `.razor` files`) is all compiled and executed on the device, just like any other app. It's no different in terms of permissions for using Swift on iOS, C++ on Windows, or Java on Android.

**Comment by Eilon** [comment]
You can learn a bit more on this video I did: https://www.youtube.com/watch?v=oNxUfPoAXac
