### ISSUE TITLE
IOS Hybrid is broken and throws exception

### ISSUE THREAD

**Issue by whann0205** [dotnet/MobileBlazorBindings#436]
If i create a new solution with either Visual Studio 2019 16.11.8 or Visual Studio 8.10.6 directly on the mac
(MacBook Air m1 2020 btw)

FirstMobileBlazorBindingsApp works out ok.
But as soon as i create FirstBlazorHybridApp it only display first half of the 
expected screen (the one which is equal to the Firstmobile thing see attached a screenshot) 
and if i click on the increment button 
and unhandled exception is raised (One or more errors occured).
Render was called before InitAsync.
![NoHybrid](https://user-images.githubusercontent.com/71807453/147786752-34ddc350-3cbf-459b-a660-ec58dcd0ec64.png)

i know it used to work with older version of VS.
Any ideas ?

**Comment by AmirImam** [comment]
Same issue happened with me on VS 2022

**Comment by whann0205** [comment]
When you create a new project with vs 2022 and choose net maui blazor targetting the ios plattform it
works instantly. Eilon?

**Comment by whann0205** [comment]
I found the problem myself. It was again a xamarin.ios sdk problem.
That nobody reacts here anymore is not so pleasant though.....

**Comment by Eilon** [comment]
@whann0205 thank you for posting the update. I have been mostly away from work for the last few weeks due to holidays and due to having 2 young kids who have to stay home because everyone is getting omicron. I do my best to quickly respond to issues but unfortunately that isn't always possible.

**Comment by whann0205** [comment]
I fully understand that there is more than work and family should always come first!
Its just that i was frustrated that i could not solve the problem and
didn´t know where to get help.
