### ISSUE TITLE
How to reuse the BlazorHybridApp

### ISSUE THREAD

**Issue by genifycom** [dotnet/MobileBlazorBindings#437]
Once we have spent time building out the BlazorHybridApp, how can we reuse this with a Web Application?

I get that the BlazorWebView is a native component which is why it can be used inside a Xamarin project, but I thought that BlazorHybrid was designed to be used in multiple environments.

This would be useful since Web Application development is SOOOO much faster than Xamarin development!

MAUI is too far away for current development, so has anyone been able to resuse the BlazorHybridApp in a DotNet core Web Application.

This link https://gunnarpeipman.com/blazor-hybrid-application-experimental/ approaches this idea but is now out of date.

Thanks

**Comment by Eilon** [comment]
Hi @genifycom , the idea is that you re-use the Blazor components from the `*.razor` files in a Blazor Hybrid App and also in a web app. You don't re-use the entire native app on the web.

**Comment by genifycom** [comment]
Hi Eilon, so if I create an RCL how can I use this in a DotNet Web Application in a dynamic (not static) fashion?

This issue is that in the AWS Lambda Environment, NONE of the current approaches work. With many clients using this approach, they are locked out of Blazor.

We cannot use Blazor Server at all and the current approach of a Blazor WebAssembly referenced from the Web application also does not work.

The only current way to deploy is statically via an S3 bucket.

We desperately need a way to deploy a razor application to AWS Lambda that can also serve up dynamic Blazor components.
MAUI will not help in this environment either.

I have been asking multiple people and so far no luck. I am looking for ideas please.
