### ISSUE TITLE
debug windows app that has a blazorwebview

### ISSUE THREAD

**Issue by dkboon01** [dotnet/MobileBlazorBindings#440]
On the hybrid app, when I load the windows desktop app and my blazor component is viewed on the desktop. Is there a way to see the css that is being used on the desktop?   Documentation says to right click and "Inspect" but I do not see this anywhere.   I just want to see the css

**Comment by Eilon** [comment]
If right-click doesn't work, then click anywhere in the webview and press <kbd>F12</kbd> and it will show the browser dev tools, which includes seeing the CSS.
