### ISSUE TITLE
this project are discontinued?

### ISSUE THREAD

**Issue by nowlights** [dotnet/MobileBlazorBindings#447]
The project been discontinued or do you have a release date?

**Comment by AhmedHemdan21** [comment]
@nowlights You can now build mobile apps using Blazor with [.NET MAUI](https://github.com/dotnet/maui)


 You can have a look at this [Article](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0) 

.NET MAUI RTM (1.0) release is this month and it's production ready
