### ISSUE TITLE
True Fullscreen on blazor windows

### ISSUE THREAD

**Issue by vhj1995** [dotnet/MobileBlazorBindings#450]
I am working on Digital Signage App. My app requires to be Full Screen.

Problem is I cannot hide the taskbar on windows.

Any ideas?

**Comment by vhj1995** [comment]
@Eilon can you shed some light on this?

**Comment by Eilon** [comment]
Hi @vhj1995 , I'm not sure how to do this, but it isn't Mobile Blazor Bindings specific. For the current release, which is based on Xamarin.Forms, it would be the same as for any Xamarin.Forms app.

**Comment by dcuccia** [comment]
Maybe something like this?

https://social.msdn.microsoft.com/Forums/vstudio/en-US/e231f5be-5233-4eee-b142-7aef50f37287/disabling-andor-hiding-windows-taskbar?forum=csharpgeneral

Per the last comment, I wouldn't recommend this for an app that's meant to be opened and closed, but for a true kiosk with auto-launch etc, it could work.

FWIW, there's also a purpose-built Windows Kiosk Mode feature:

https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app

**Comment by vhj1995** [comment]
Thanks for inputs. @dcuccia and @Eilon
