### ISSUE TITLE
VS 2022 Community is forever Installing SDK Components and never completes.

### ISSUE THREAD

**Issue by mkamoski** [dotnet/MobileBlazorBindings#479]
VS 2022 Community is forever Installing SDK Components and never completes.

Using VS 2022 fully patched.

Ran SDK Manager and installed virtually all SDKs.

VS keeps asking for SDK 28 which is NOT available in SDK Manager.

Blocked.

**Comment by Eilon** [comment]
Hi @mkamoski , for issues with Visual Studio and the installer, please use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue. That way it will get to the routed to the right that owns this experience in VS.
